; PlatformIO Project Configuration File

[env:freenove_esp32_wrover]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
lib_deps =
    espressif/esp32-camera
    h2zero/NimBLE-Arduino@^1.4.1
