; PlatformIO Project Configuration File

[env:freenove_esp32_wrover]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
lib_deps =
    espressif/esp32-camera
    h2zero/NimBLE-Arduino@^2.0.0

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_port = auto
upload_port = auto
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DBOARD_XIAO_ESP32S3
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
lib_deps =
    espressif/esp32-camera
    h2zero/NimBLE-Arduino@^2.0.0
